# -*- coding: utf-8 -*-
"""RCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOpQptoFKX3HUbx-QW5kfyjGL6EG1Fgo
"""

import cv2
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import img_to_array
from google.colab.patches import cv2_imshow

# --------------------------
# Load pre-trained CNN (VGG16) for feature extraction (excluding classifier layers)
base_model = VGG16(weights='imagenet', include_top=True)
feature_extractor = Model(inputs=base_model.input, outputs=base_model.get_layer("fc1").output)

# --------------------------
# 1. Selective Search: Region Proposals
# --------------------------
def get_region_proposals(image):
    ss = cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
    ss.setBaseImage(image)
    ss.switchToSelectiveSearchFast()
    rects = ss.process()
    return rects[:2000]  # Top 2000 proposals

# --------------------------
# 2. Feature Extraction from CNN
# --------------------------
def extract_features(image, box):
    x, y, w, h = box
    roi = image[y:y+h, x:x+w]
    roi = cv2.resize(roi, (224, 224))
    roi = img_to_array(roi)
    roi = np.expand_dims(roi, axis=0)
    roi = preprocess_input(roi)
    features = feature_extractor.predict(roi)
    return features[0]

# --------------------------
# 3. Training Example
# --------------------------
X_train = np.random.rand(10, 4096)
y_train = ['car', 'car', 'bus', 'car', 'bike', 'car', 'bus', 'bike', 'car', 'bus']
svm = SVC(probability=True)
bbox_train = []  # Bounding box regression targets

# Sample image and annotations
image = cv2.imread("/content/sample_data/car.png")
gt_boxes = [(50, 30, 150, 150)]  # format: x, y, w, h
gt_labels = ["car"]

proposals = get_region_proposals(image)

for box in proposals:
    x, y, w, h = box
    for i, gt in enumerate(gt_boxes):
        gx, gy, gw, gh = gt

        # Calculate IoU (for training positive samples)
        ix = max(x, gx)
        iy = max(y, gy)
        ax = min(x+w, gx+gw)
        ay = min(y+h, gy+gh)
        inter_area = max(0, ax - ix) * max(0, ay - iy)
        union_area = w*h + gw*gh - inter_area
        iou = inter_area / union_area

        if iou > 0.5:  # Positive match
            feature = extract_features(image, box)
            X_train.append(feature)
            y_train.append(gt_labels[i])

            # Bounding box regression targets: dx, dy, dw, dh
            dx = (gx + gw/2 - (x + w/2)) / w
            dy = (gy + gh/2 - (y + h/2)) / h
            dw = np.log(gw / w)
            dh = np.log(gh / h)
            bbox_train.append([dx, dy, dw, dh])

# --------------------------
# 4. Train SVM & BBox Regressor
# --------------------------
svm = SVC(probability=True)
svm.fit(X_train, y_train)

regressor = LinearRegression()
regressor.fit(X_train, bbox_train)

# --------------------------
# 5. Inference
# --------------------------
test_img = cv2.imread("/content/sample_data/car.png")
proposals = get_region_proposals(test_img)

for box in proposals:
    feature = extract_features(test_img, box)
    pred_label = svm.predict([feature])[0]
    prob = svm.predict_proba([feature]).max()

    if prob > 0.8:
        dx, dy, dw, dh = regressor.predict([feature])[0]
        x, y, w, h = box
        cx, cy = x + w / 2, y + h / 2

        # Apply regression to adjust bbox
        cx += dx * w
        cy += dy * h
        w *= np.exp(dw)
        h *= np.exp(dh)
        x = int(cx - w/2)
        y = int(cy - h/2)

        cv2.rectangle(test_img, (x, y), (x + int(w), y + int(h)), (0, 255, 0), 2)
        cv2.putText(test_img, pred_label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

cv2_imshow(test_img)

import cv2
import numpy as np
import os
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.models import Model
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

# Sample images (just as example placeholders)
image_paths = [
    "/content/sample_data/car.png",
    "/content/bike.jpg",
    "/content/bus.jpg"
]

# Corresponding labels and ground truth bounding boxes (manually given for demo)
labels = ["car", "bike", "bus"]
gt_boxes = [  # (x, y, w, h)
    (50, 50, 200, 150),  # car box
    (30, 30, 120, 100),  # bike box
    (70, 70, 220, 160)   # bus box
]

base_model = VGG16(weights='imagenet')
feature_extractor = Model(inputs=base_model.input, outputs=base_model.get_layer('fc1').output)

def get_region_proposals(img):
    ss = cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
    ss.setBaseImage(img)
    ss.switchToSelectiveSearchFast()
    rects = ss.process()
    return rects[:100]  # limit to 100 regions
def extract_features(image, box):
    x, y, w, h = box
    roi = image[y:y+h, x:x+w]
    roi = cv2.resize(roi, (224, 224))
    roi = np.expand_dims(roi, axis=0)
    roi = preprocess_input(roi)
    features = feature_extractor.predict(roi)
    return features.flatten()

X_train = []
y_train = []

for idx, path in enumerate(image_paths):
    img = cv2.imread(path)
    boxes = get_region_proposals(img)
    gt = gt_boxes[idx]

    for box in boxes:
        x, y, w, h = box
        iou = calculate_iou(gt, (x, y, w, h))
        if iou > 0.5:
            feat = extract_features(img, box)
            X_train.append(feat)
            y_train.append(labels[idx])

def calculate_iou(box1, box2):
    x1, y1, w1, h1 = box1
    x2, y2, w2, h2 = box2

    xi1 = max(x1, x2)
    yi1 = max(y1, y2)
    xi2 = min(x1+w1, x2+w2)
    yi2 = min(y1+h1, y2+h2)

    inter_area = max(0, xi2 - xi1) * max(0, yi2 - yi1)
    box1_area = w1 * h1
    box2_area = w2 * h2
    union = box1_area + box2_area - inter_area

    return inter_area / union

le = LabelEncoder()
y_encoded = le.fit_transform(y_train)

svm = SVC(probability=True)
svm.fit(X_train, y_encoded)

test_image = cv2.imread("/content/sample_data/car.png")
test_boxes = get_region_proposals(test_image)

for box in test_boxes:
    x, y, w, h = box
    feat = extract_features(test_image, (x, y, w, h))
    prob = svm.predict_proba([feat])[0]
    pred = svm.predict([feat])[0]

    if max(prob) > 0.8:
        label = le.inverse_transform([pred])[0]
        cv2.rectangle(test_image, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(test_image, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

plt.imshow(cv2.cvtColor(test_image, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()